name: publish

on:
  push:
    branches:
      - master

jobs:
  release:
    name: publish
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: node
        uses: actions/setup-node@master
        with:
          node-version: 14.x
          registry-url: https://registry.npmjs.org

      - name: installDeps
        run: npm i

      - name: build
        run: npm run build

      - name: publish
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
